services:
    type: web
    name: FineTuning-bot
    env: python
    build:
      commands:
        - mkdir -p model_BERTimbau tokenizer_BERTimbau
        - gdown "https://drive.google.com/uc?id=1Tq0RydIdJ6qHUwrWKAz8P8h6zu0Ao_GG&export=download" -O model_BERTimbau/model.safetensors
        - gdown "https://drive.google.com/uc?id=1NyqP2RD8blWEaouRCiSJJiVf145L-cQM&export=download" -O model_BERTimbau/config.json
        - gdown "https://drive.google.com/uc?id=1-vNuRSo6vDhZYhjDwc2PhIlc3dQZFSbn&export=download" -O tokenizer_BERTimbau/vocab.txt
        - gdown "https://drive.google.com/uc?id=1IpacRV4iVFVzARti1-k3kJu71gLs6qgM&export=download" -O tokenizer_BERTimbau/tokenizer_config.json
        - gdown "https://drive.google.com/uc?id=1tQNqk6T1dHvT6IEcM6M02ADfxuRM_Afs&export=download" -O tokenizer_BERTimbau/special_tokens_map.json
      startCommand: python bot/telegram/server.py 